name: Bug Report
description: Create a report to help us improve workflow-playbooks
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report a bug in workflow-playbooks!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what you observed vs what you expected.
    validations:
      required: true
